/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_whole_process_img */

#ifndef _Included_com_example_whole_process_img
#define _Included_com_example_whole_process_img
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_whole_process_img
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_whole_process_1img_getEdge
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_whole_process_img
 * Method:    gray
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_whole_process_1img_gray
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_whole_process_img
 * Method:    contours
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_whole_process_1img_contours
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_whole_process_img
 * Method:    watershed
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_whole_process_1img_watershed
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
